### ISSUE TITLE
Parsing of CDDL fails unexpectedly

### ISSUE THREAD

**Issue by caugner** [christian-bromann/cddl#107]
Parsing of webdriver-bidi CDDL file fails.

1. Download https://github.com/w3c/webdriver-bidi/actions/runs/12085975317/artifacts/2254085949
2. Extract `cddl.zip`.
3. Run `npm install cddl`
4. Run `node` and type `import('cddl').then(({parse}) => parse('cddl/all.cddl'))`

Yields this error:

```
> Uncaught:
Error: cddl/all.cddl:135:34 - error: group identifier expected, received "{"Type":"}","Literal":"}"}"

session.AutodetectProxyConfiguration = (
                                  ^
                                  |

    at Parser.parserError (file:///path/to/node_modules/cddl/build/parser.js:731:16)
    at Parser.parseAssignments (file:///path/to/node_modules/cddl/build/parser.js:52:24)
    at Parser.parse (file:///path/to/node_modules/cddl/build/parser.js:721:32)
    at parse (file:///path/to/node_modules/cddl/build/index.js:5:19)
```

Note: The [cddl crate](https://crates.io/crates/cddl) parses the file without issues.

**Comment by christian-bromann** [comment]
@caugner thanks for flagging this issue. I am not sure when I get the time to look at this so if this is a pressing issue for you, any support would be appreciated.

**Comment by cabo** [comment]
I don't know about the provenance of cddl.js, but the old cddl tool needed a little help with two rules:

``` cddl
script.RegExpRemoteValue = ({
        ? handle: script.Handle,
        ? internalId: script.InternalId,
    }) .and script.RegExpLocalValue
script.DateRemoteValue = ({
        ? handle: script.Handle,
        ? internalId: script.InternalId,
    }) .and script.DateLocalValue
```

You can get this help from the new ool:

```
cddlc -tcddl all.cddl
```

Grüße, Carsten

**Comment by cabo** [comment]
Oh, there is a stray semicolon in line 127; maybe cddl.js is allergic to empty comments?
